### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by salamander2** [jakubboucek/docker-lamp-devstack#58]
You have two images for your LAMP while everyone else just has one. 

- lamp-devstack-php
- lamp-devstack-mysql

I think you need to explain the reasoning behind this, and if one needs to download both.  I don't believe that it is stated anywhere that you need both images.

If so, how do the two images connect? What does the user have to do?  

Thanks.

**Comment by salamander2** [comment]
P.S.  Is there a MySQL version (instead of MariaDB)?

**Comment by jakubboucek** [comment]
Hi @salamander2,
try to read documentation at [`Readme.md`](https://github.com/jakubboucek/docker-lamp-devstack/blob/master/README.md), where also writed:

1. There is two images (see [**Built images**](https://github.com/jakubboucek/docker-lamp-devstack/blob/master/README.md#built-images) section).
2. How to use and combine both images is explained at [**Basic usage**](https://github.com/jakubboucek/docker-lamp-devstack/blob/master/README.md#basic-usage) section – just use `Docker Compose` to run both images as single compose.

> Is there a MySQL version (instead of MariaDB)?

No, it's not. I know the chosen names can be confusing, it's my fault because historical evolution of Images.

Did I manage to explain them all?

**Comment by salamander2** [comment]
Yes, you mention that there are two images, but it is never said that both of them are necessary. I cannot just choose which image I want to run. I need both of them.  The `docker compose` is useful, but ONLY if I look at the docker-compose.yaml file (which I didn't do until now).  I now understand more of what you're doing.

However, I think you could clarify things by making the following two changes:


## Built images

There are two images and you will need both of them. 

- PHP: [`jakubboucek/lamp-devstack-php`](https://hub.docker.com/r/jakubboucek/lamp-devstack-php)
- MySQL: [`jakubboucek/lamp-devstack-mysql`](https://hub.docker.com/r/jakubboucek/lamp-devstack-mysql)


## Basic usage
After you've pulled both images, with the desired tag/version, 
copy the [`docker-compose.yml`](docker-compose.yml) file ([download](https://downfile.github.io/download?url=https%3A//raw.githubusercontent.com/jakubboucek/docker-lamp-devstack/master/docker-compose.yml&file=docker-compose.yml))
to your project's root (you don't need to clone/download the whole repo, just copy that one file).

Call `docker compose up`. After docker container runs, your project will be served at http://localhost:8080/.
...


---------------

Thanks for doing this and for replying.  I'm wondering what makes your LAMP stack better than the other ones. You might want to add something at the top of your readme.md about that, but if not, I'd be happy to know.  I'm in the process of learning Docker.

**Comment by jakubboucek** [comment]
> After you've pulled both images, with the desired tag/version,

The point is: **You DON'T need to pull both images first.** 🎉🎊👍

The `docker compose` command takes care of it for you by a ✨magic✨. 

> I'm wondering what makes your LAMP stack better than the other ones.

Hm. The main reason for that images is my own requirements. I make it for myself. That's mean – I have no ambitions to make it "objectively the best" just make it great for my work. And I hope it's usefull for somebody else.

Main differences against other projects:

- zero-configuration way - just copy one `docker-compose.yml` and it's run,
- share images between projects - no more need to build extra image for each web project, this is an unnecessary waste of resources,
- Apache for simple support Rewrite rules,
- Apache module mode for simplest run (lower performance but single root process make composition too simple to manage for local development stack),
- based on official images - a high quality of support can be expected in future and my images is very simple extendable,
- minimal intervention to default configuration - i changed only necessary parameters, all others keeps in default values to preserve base environment,
- highest possible compatibility with well known webhosting configuration,
- prepared for high secure design of application (where Document Root in **under** the filesystem root).

**Comment by salamander2** [comment]
That all makes sense.

> share images between projects - no more need to build extra image for each web project, this is an unnecessary waste of resources,

At some point in the future, I'll have to figure out what this means. I assume that MySQL is using an external volume for the database so that the data persists if the container needs to be restarted.     

If I had two vastly different PHP apps, wouldn't I need to spin up two containers, and somehow get the PHP code into each one? Wouldn't this be done using a Dockerfile, thus making a new image for each app?

Or are you saying that everything goes in one container and then we just use Apache2 virtualhosts to run the various programs? (which is what I'm doing with my https://demo.iquark.ca ).  But then the whole point of containerization and encapuslation is lost - the various apps are in the same container and interact with each other (possibly in a bad way).

**Comment by jakubboucek** [comment]
> At some point in the future, I'll have to figure out what this means. I assume that MySQL is using an external volume for the database so that the data persists if the container needs to be restarted.

Yep. Lokk to the last one row at `docker-compose.yml` file, here is volume which is mounting MySQL's data from host side.

> If I had two vastly different PHP apps, wouldn't I need to spin up two containers, and somehow get the PHP code into each one? Wouldn't this be done using a Dockerfile, thus making a new image for each app?

I think you are confusing the terms `image` and `container`. As I said, only Images are shared. But containers must me separated for each project. Try to read mode about means.

> Or are you saying that everything goes in one container and then we just use Apache2 virtualhosts to run the various programs? (which is what I'm doing with my https://demo.iquark.ca ). But then the whole point of containerization and encapuslation is lost - the various apps are in the same container and interact with each other (possibly in a bad way).

You right. The Docker is (imprecisely said) replacement for Virtualhosts. Here is no more setup Apache – here is relation 1:1 – 1 Virtualhost to 1 Docker container. When you need to run another separated PHP application, just run it with separated container.

But you example at https://demo.iquark.ca is different: here is mode application on same host (same virtualhost), the applications are separated by `URI path`. It can be hosted at same Virtualhost.

**Comment by salamander2** [comment]
Thank you.

You're right. The only thing that I'm using VirtualHost for is to change the document root for the laravel application.

However, on the iquark.ca server I have

- iquark.ca
- iquark.ca:8009
- quarkphysics.ca
- clarissaharwood.com

and a couple of other things.
