### ISSUE TITLE
lamp-devstack-php not connecting to mysql

### ISSUE THREAD

**Issue by salamander2** [jakubboucek/docker-lamp-devstack#61]
Hi!

I'm trying to customize your lamp-devstack-php, but I cannot get it to connect. Can you help me? Thanks.
I'm rebuilding your image exactly using your exact Dockerfile and everything.

The `docker-compose.yml` has this one single change from your original docker-compose.yml:

```
services:
    web:
        #image: jakubboucek/lamp-devstack-php
        image: harwoomi/lamp-devstack-php
```

:star: My app works perfectly if I use **your** image (jakubboucek/lamp-devstack-php)

However, if I download your Dockerfile-8.3 and your files: 
`core.ini
opcache-7.4.ini
opcache.ini
sources.list-bookworm`

and then I run 
`docker build --progress plain -t harwoomi/lamp-devstack-php ./`  (using your dockerfile which I just rename to Dockerfile)

Everything builds fine, but the php container cannot connect to the mysql container.  I don't know why. I don't know how to troubleshoot it either. 

Here's what I do. I "exec" into the container harwoomi/lamp-devstack-php and then run `php -a`. Then I type the following command and get this error.   (BUT I don't get any errors if I "exec" into jakubboucek/lamp-devstack-php)

```
php > $mysqli = new mysqli('mysqldb', 'root', 'devstack', 'default');

Warning: mysqli::__construct(): php_network_getaddresses: getaddrinfo for mysqldb failed: Name or service not known in php shell code on line 1

Warning: Uncaught mysqli_sql_exception: php_network_getaddresses: getaddrinfo for mysqldb failed: Name or service not known in php shell code:1
Stack trace:
#0 php shell code(1): mysqli->__construct('mysqldb', 'root', Object(SensitiveParameterValue), 'default')
#1 {main}
  thrown in php shell code on line 1
```

The network is created by "docker compose up" and is the same whether I use your image or my image. So, the network does not seem to be the problem.

**Comment by salamander2** [comment]
Okay, I found out the problem. There are two things that are not clear in the Docker documentation. You might want to add them to your documentation.

1\. In the `docker-compose-yml` file, the name of the SQL container MUST be "mysqld". This is because PHP uses this container name to connect to the SQL database:  `$mysqli = new mysqli('mysqldb', 'root', 'devstack', 'default');` If you change the name of the container, then you have to change your PHP code (or a PHP config file that you use). Note that even though `docker compose` creates the container name as &lt;project&gt;-mysqld-1 , it still works.


2\. To load your own database, you'll have to make your own image that is extends the lamp-devstack-mysql image.  Here's how you do it. Make a Dockerfile like the following:

```FROM jakubboucek/lamp-devstack-mysql

COPY ICSuploadDB.clean.sql /docker-entrypoint-initdb.d/
RUN docker-entrypoint.sh

# docker build -t harwoomi/lamp-mysql . 
```

@jakubboucek  , you can close this now.  I'm not sure what I can do to help you out.  The only thing that I can think of is if you need any English proof-reading, to make sure that something you write is in correct English. I'm happy to do that for you.

Thanks for making this project.

**Comment by jakubboucek** [comment]
Hi Salamander. 

The case you talk about is related to Docker basics knowledge. It's not related to this repo. Here is no reason to update documentation of this images.

The Images and Compose files are published prepared for fast usage. **And it's prepared to use "as is".**

That means: when you make modification **out of suggested range**, it's on your own risk and you should to know you doing. If I were to start describing and explaining the basic principles of how Docker works here, I would then have to also explain all the other mechanisms of Docker and that would mean that I would have to copy the [entire Docker documentation](https://docs.docker.com/) here.

I am so sorry for dissenting opinion and thanks for understanding

**Comment by salamander2** [comment]
:+1:
